import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ['500'],
  // style:["italic"],
  display: "swap",
});

export const metadata = {
  title: "IVidhan Tourism Agency.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
